import { Network } from '@orbs-network/ton-access';
import dotenv from 'dotenv';
dotenv.config();

let {
    NETWORK,
    ENCRYPTION_PRIVATE_KEY,
    ENCRYPTION_PUBLIC_KEY,
    TON_API,
    TON_API_TOKEN,
    MONGODB_URI,
    SENTRY_DSN,
    JWT_SECRET,
    SESSION_SECRET,
    ACCESS_TOKEN_TTL,
    REFRESH_TOKEN_TTL,
    TG_BOT_TOKEN,
    FILEBASE_ACCESS_KEY,
    FILEBASE_SECRET_KEY,
    REDIS_URL,
    REDIS_TOKEN,
    BASE_URL,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    DEV_BASE_URL,
    CLIENT_BASE_URL,
    COLLECTION_ADDR,
    MARKETPLACE_ADDR,
    TON_WEBSOCKET_URL,
    MNEMONIC,
} = process.env;

NETWORK = NETWORK == 'mainnet' ? NETWORK : 'testnet';
TON_API = TON_API || 'https://testnet.tonapi.io/v2'; // defaults to testnet
MONGODB_URI = MONGODB_URI || 'mongodb://localhost:27017/quyx';
JWT_SECRET = JWT_SECRET || 'super_secret_stuff_hahaha';
SESSION_SECRET = SESSION_SECRET || 'super_secret_stuff_hahaha';
ACCESS_TOKEN_TTL = ACCESS_TOKEN_TTL || '5m';
REFRESH_TOKEN_TTL = REFRESH_TOKEN_TTL || '1y';
DEV_BASE_URL = DEV_BASE_URL || 'http://localhost:5174';
CLIENT_BASE_URL = CLIENT_BASE_URL || 'http://localhost:5173';
COLLECTION_ADDR = COLLECTION_ADDR || 'EQDq-1U0voeQ6gx69SXq9jOZlk2PQdCl6sj3UYNHhqk9Bw3S';
MARKETPLACE_ADDR = MARKETPLACE_ADDR || 'EQBj6eMvEXYR_ql6NTUANC4WEJ0ZGAVp1KElijVGAoftIVc3';
TON_WEBSOCKET_URL = TON_WEBSOCKET_URL || 'wss://testnet.tonapi.io/v2/websocket';
const IS_TESTNET = NETWORK === 'mainnet' ? false : true;

BASE_URL = BASE_URL || 'http://localhost:3000';
const GITHUB_REDIRECT_URL = `${BASE_URL}/auth/github/callback`;
const GOOGLE_REDIRECT_URL = `${BASE_URL}/auth/google/callback`;

export default {
    NETWORK: NETWORK as Network,
    ENCRYPTION_PRIVATE_KEY,
    ENCRYPTION_PUBLIC_KEY,
    TON_API,
    TON_API_TOKEN,
    IS_TESTNET,
    MONGODB_URI,
    SENTRY_DSN,
    JWT_SECRET,
    ACCESS_TOKEN_TTL,
    REFRESH_TOKEN_TTL,
    TG_BOT_TOKEN,
    FILEBASE_ACCESS_KEY,
    FILEBASE_SECRET_KEY,
    REDIS_URL,
    REDIS_TOKEN,
    BASE_URL,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GITHUB_REDIRECT_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URL,
    SESSION_SECRET,
    DEV_BASE_URL,
    CLIENT_BASE_URL,
    COLLECTION_ADDR,
    MARKETPLACE_ADDR,
    TON_WEBSOCKET_URL,
    MNEMONIC,
};
